apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-stage-certificate
  namespace: cert-manager
spec:
  secretName: letsencrypt-stage-secret
  dnsNames:
  - cfs-lending.myvnc.com
  issuerRef:
    name: letsencrypt-stage-issuer
    kind: ClusterIssuer
    group: cert-manager.io