apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-prd-certificate
  namespace: kubernetes-dashboard
spec:
  secretName: letsencrypt-prd-certificate-secret
  dnsNames:
  - cfs-lending.myvnc.com
  issuerRef:
    name: letsencrypt-prd-issuer
    kind: ClusterIssuer
    group: cert-manager.io
