apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-stage-certificate
  namespace: kubernetes-dashboard
spec:
  secretName: letsencrypt-stage-secret
  commonName: letsencrypt-stage-secret
  dnsNames:
  - cfs-lending.myvnc.com
  issuerRef:
    name: letsencrypt-stage-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"  
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "kubernetes-dashboard"  # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "kubernetes-dashboard" # Control auto-reflection namespace