apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak
spec:
  secretName: letsencrypt-keycloak-certificate-secret
  dnsNames:
  - cfs-lending.myvnc.com
  issuerRef:
    name: letsencrypt-prd-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: docker.io/mihaibob/keycloak:18.0.0-legacy
        env:
        - name: KEYCLOAK_LOGLEVEL
          value: "DEBUG"
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin@123"
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "admin@12"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: "KEYCLOAK_ADMIN_URL"
          value: "https://cfs-lending.myvnc.com/lending/auth/realms/master/admin/"
        - name: "KEYCLOAK_FRONTEND_URL"
          value: "https://cfs-lending.myvnc.com/lending/auth/"
        - name: DB_VENDOR
          value: "mysql"
        - name: DB_ADDR
          value: "mysql"
        - name: DB_DATABASE
          value: "keycloak"
        - name: DB_USER
          value: "keycloak"
        - name: DB_PASSWORD
          value: "keycloak@123"
        - name: JDBC_PARAMS
          value: "serverTimezone=UTC"
        ports:
        - name: "http"
          protocol: TCP
          containerPort: 8080
        - name: "https"
          protocol: TCP
          containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak  
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: keycloak
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-buffer-size: "12k"
  name: keycloak-ingress
  labels:
    app: keycloak
spec:
  tls:
  - hosts:
    - cfs-lending.myvnc.com
    secretName: letsencrypt-keycloak-certificate-secret
  rules: 
    # https://cfs-lending.myvnc.com/lending/auth/
    # https://cfs-lending.myvnc.com/lending/auth/admin/master/console/
    # https://cfs-lending.myvnc.com/lending/auth/realms/master/account/#/
    - host: cfs-lending.myvnc.com
      http:
        paths:
          - path: "/lending/(.*)"
            pathType: ImplementationSpecific
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
