apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak
spec:
  secretName: letsencrypt-keycloak-certificate-secret
  dnsNames:
  - cfs-lending.myvnc.com
  issuerRef:
    name: letsencrypt-prd-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: docker.io/mihaibob/keycloak:18.0.0-legacy
        env:
        - name: KEYCLOAK_LOGLEVEL
          value: "DEBUG"
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "test@123"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        ports:
        - name: http
          protocol: TCP
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak  
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: keycloak
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  annotations: 
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: keycloak-ingress
  labels:
    app: keycloak
spec:
  tls:
  - hosts:
    - cfs-lending.myvnc.com
    secretName: letsencrypt-keycloak-certificate-secret
  rules: 
    - host: cfs-lending.myvnc.com
      http:
        paths:
          - path: /login(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
