---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: arm64v8/phpmyadmin:latest
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysql
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlsecret
                  key: ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  type: ClusterIP
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-phpmyadmin-certificate
spec:
  secretName: letsencrypt-phpmyadmin-certificate-secret
  dnsNames:
  - cfs-lending.myvnc.com
  issuerRef:
    name: letsencrypt-prd-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phpmyadmin-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    app: phpmyadmin
spec: 
  tls:
    - hosts:
      - cfs-lending.myvnc.com
      secretName: letsencrypt-phpmyadmin-certificate-secret
  rules: 
    - host: cfs-lending.myvnc.com
      http:
        paths:
          - path: /phpmyadmin(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: phpmyadmin
                port:
                  number: 80
